import  mongoose  from "mongoose";
const Schema=mongoose.Schema;

let RealEstate= new Schema({
    Id:{
        type:Number
    },
    Name:{
        type:String
    },
    Type:{
        type:String
    },
    City:{
        type:String
    },
    Municipality:{
        type:String
    },
    Microlocation:{
        type:String
    },
    Street:{
        type:String
    },
    Area:{
        type:Number
    },
    Rooms:{
        type:Number
    },
    ConstructionYear:{
        type:Number
    },
    State:{
        type:String
    },
    Heating:{
        type:String
    },
    Floor:{
        type:Number
    },
    TotalFloors:{
        type:Number
    },
    Parking:{
        type:String
    },
    MonthlyUtilities:{
        type:Number
    },
    Price:{
        type:Number
    },
    About:{
        type:String
    },
    Characteristics:{
        type:Array
    },
    Pictures:{
        type:Array
    },
    Oglasavac:{
        type:String
    },
    Agencija:{
        type:String
    },
    Sold:{
        type:Boolean
    }
})
export default mongoose.model('RealEstate',RealEstate,'realestates')